let appData = null;
let currentCategoryData = null;

document.addEventListener('DOMContentLoaded', async () => {
    const spinner = document.getElementById('loading-spinner');
    const selector = document.getElementById('stream-selector');
    
    spinner.classList.remove('hidden');
    
    try {
        // Fetch the JSON generated by Python
        const response = await fetch('data/syllabus_data.json');
        if (!response.ok) throw new Error("Data file not found. Run GitHub Action.");
        appData = await response.json();
        renderCategories();
    } catch (error) {
        console.error(error);
        selector.innerHTML = `
            <div class="col-span-3 text-center text-red-400 bg-red-900/20 p-6 rounded-lg border border-red-500/30">
                <h3 class="text-xl font-bold">Data Not Found</h3>
                <p class="mt-2">Please go to your GitHub Repo > Actions > Run Workflow to generate the syllabus data.</p>
            </div>
        `;
    } finally {
        spinner.classList.add('hidden');
    }
});

function renderCategories() {
    const container = document.getElementById('stream-selector');
    container.innerHTML = '';

    // Loop through Science, Commerce, Arts
    Object.keys(appData).forEach(stream => {
        const categories = appData[stream];
        Object.keys(categories).forEach(catKey => {
            const data = categories[catKey];
            
            const card = document.createElement('div');
            card.className = 'glass-panel p-6 rounded-xl stream-card flex flex-col items-center justify-center text-center h-48';
            card.innerHTML = `
                <div class="bg-blue-500/20 p-4 rounded-full mb-4 text-blue-400">
                    <i class="fa-solid fa-layer-group text-2xl"></i>
                </div>
                <h3 class="text-xl font-bold text-white">${stream}</h3>
                <p class="text-sm text-gray-400">${catKey}</p>
            `;
            card.onclick = () => loadRoadmap(data);
            container.appendChild(card);
        });
    });
}

function loadRoadmap(data) {
    currentCategoryData = data; // Store for PDF download
    
    document.getElementById('stream-selector').classList.add('hidden');
    document.getElementById('roadmap-view').classList.remove('hidden');

    // Populate Master Node
    document.getElementById('master-name').innerText = data.master.name;
    document.getElementById('master-desc').innerText = data.master.description || "All India Standard Exam";
    
    // Populate Subjects List
    const subjectList = document.getElementById('master-subjects');
    subjectList.innerHTML = '';
    const subjects = data.master.syllabus ? Object.keys(data.master.syllabus) : [];
    subjects.forEach(sub => {
        subjectList.innerHTML += `<li class="flex items-center gap-2"><i class="fa-solid fa-check text-green-400"></i> ${sub}</li>`;
    });

    // Populate Satellites
    const satList = document.getElementById('satellite-list');
    satList.innerHTML = '';
    
    if (data.satellites && data.satellites.length > 0) {
        data.satellites.forEach(sat => {
            satList.innerHTML += `
                <div class="glass-panel p-4 rounded-lg border-l-4 border-purple-500">
                    <div class="flex justify-between items-start">
                        <h4 class="font-bold text-lg text-white">${sat.name}</h4>
                        <span class="text-xs bg-purple-500/20 text-purple-300 px-2 py-1 rounded">Alt</span>
                    </div>
                    <p class="text-sm text-gray-400 mt-2"><strong class="text-gray-300">Deviation:</strong> ${sat.deviation}</p>
                </div>
            `;
        });
    } else {
        satList.innerHTML = `<p class="text-gray-500 italic">No major deviations. Follow Master Syllabus.</p>`;
    }
}

function resetView() {
    document.getElementById('roadmap-view').classList.add('hidden');
    document.getElementById('stream-selector').classList.remove('hidden');
    currentCategoryData = null;
}

window.downloadCurrentSyllabus = () => {
    if (window.generatePDF && currentCategoryData) {
        window.generatePDF(currentCategoryData);
    } else {
        alert("PDF Generator not loaded");
    }
};
